/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.DeleteTask;
import io.swagger.model.Task;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-11-21T14:50:45.063Z")

@Api(value = "task", description = "the task API")
@RequestMapping(value = "/timesheet")
public interface TaskApi {

    @ApiOperation(value = "Add a new Task to the timesheet", nickname = "addTask", notes = "", tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/task",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addTask(@ApiParam(value = "Task object that needs to be added to the sheet" ,required=true )  @Valid @RequestBody Task body);


    @ApiOperation(value = "delete Task from timesheet", nickname = "deleteTask", notes = "", tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/task",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTask(@ApiParam(value = "Task object that needs to be added to the sheet" ,required=true )  @Valid @RequestBody DeleteTask body);


    @ApiOperation(value = "Update an existing Task", nickname = "updateTask", notes = "", tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "task not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/task",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateTask(@ApiParam(value = "Task object that needs to be updated in the sheet" ,required=true )  @Valid @RequestBody Task body);

}
